package comms

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/Ad3bay0c/routex/tools"
)

// SendEmailTool sends emails via either SendGrid or Resend.
//
// Two providers are supported — choose via agents.yaml:
//
//	tools:
//	  - name: "send_email"
//	    api_key: "env:SENDGRID_API_KEY"
//	    extra:
//	      provider:   "sendgrid"          # or "resend"
//	      from_email: "agent@example.com"
//	      from_name:  "Routex Agent"      # optional
//
// SendGrid — https://sendgrid.com (free: 100 emails/day)
// Resend   — https://resend.com   (free: 3,000 emails/month)
//
// Both providers share the same Tool interface — swap by changing
// provider: in agents.yaml with no code changes.
type SendEmailTool struct {
	provider  emailProvider
	fromEmail string
	fromName  string
}

// emailProvider is the internal interface both SendGrid and Resend satisfy.
// Keeping it internal means callers only ever see SendEmailTool.
type emailProvider interface {
	send(ctx context.Context, to, subject, body string, isHTML bool) (messageID string, err error)
	name() string
}

type sendEmailInput struct {
	To      string `json:"to"`
	Subject string `json:"subject"`
	Body    string `json:"body"`
	IsHTML  bool   `json:"is_html,omitempty"`
}

type sendEmailOutput struct {
	Success   bool   `json:"success"`
	MessageID string `json:"message_id,omitempty"`
	Provider  string `json:"provider"`
	To        string `json:"to"`
	Subject   string `json:"subject"`
}

// NewSendEmailTool builds a SendEmailTool for the given provider.
// providerName must be "sendgrid" or "resend".
func NewSendEmailTool(providerName, apiKey, fromEmail, fromName string) (*SendEmailTool, error) {
	if fromEmail == "" {
		return nil, fmt.Errorf("send_email: from_email is required")
	}

	var p emailProvider
	switch strings.ToLower(providerName) {
	case "sendgrid", "":
		p = &sendGridProvider{apiKey: apiKey}
	case "resend":
		p = &resendProvider{apiKey: apiKey}
	default:
		return nil, fmt.Errorf(
			"send_email: unknown provider %q — valid values: sendgrid, resend",
			providerName,
		)
	}

	return &SendEmailTool{
		provider:  p,
		fromEmail: fromEmail,
		fromName:  fromName,
	}, nil
}

func (t *SendEmailTool) Name() string { return "send_email" }

func (t *SendEmailTool) Schema() tools.Schema {
	return tools.Schema{
		Description: "Send an email to a recipient via " + t.provider.name() + ". " +
			"Use to deliver reports, summaries, or alerts generated by the agent crew. " +
			"Supports plain text and HTML content.",
		Parameters: map[string]tools.Parameter{
			"to": {
				Type:        "string",
				Description: "Recipient email address. Example: 'user@example.com'",
				Required:    true,
			},
			"subject": {
				Type:        "string",
				Description: "Email subject line.",
				Required:    true,
			},
			"body": {
				Type:        "string",
				Description: "Email body. Plain text by default. Set is_html to true to send HTML.",
				Required:    true,
			},
			"is_html": {
				Type:        "boolean",
				Description: "Send body as HTML. Default: false (plain text).",
				Required:    false,
			},
		},
	}
}

func (t *SendEmailTool) Execute(ctx context.Context, input json.RawMessage) (json.RawMessage, error) {
	var params sendEmailInput
	if err := json.Unmarshal(input, &params); err != nil {
		return nil, fmt.Errorf("send_email: invalid input: %w", err)
	}
	if strings.TrimSpace(params.To) == "" {
		return nil, fmt.Errorf("send_email: to is required")
	}
	if strings.TrimSpace(params.Subject) == "" {
		return nil, fmt.Errorf("send_email: subject is required")
	}
	if strings.TrimSpace(params.Body) == "" {
		return nil, fmt.Errorf("send_email: body is required")
	}

	messageID, err := t.sendWithFrom(ctx, params.To, params.Subject, params.Body, params.IsHTML)
	if err != nil {
		return nil, err
	}

	return json.Marshal(sendEmailOutput{
		Success:   true,
		MessageID: messageID,
		Provider:  t.provider.name(),
		To:        params.To,
		Subject:   params.Subject,
	})
}

var _ tools.Tool = (*SendEmailTool)(nil)

// ── Sendgrid provider ───────────────────────────────────────────────
type sendGridProvider struct {
	apiKey string
	client *http.Client
}

func (p *sendGridProvider) name() string { return "sendgrid" }

func (p *sendGridProvider) send(ctx context.Context, to, subject, body string, isHTML bool) (string, error) {
	if p.client == nil {
		p.client = &http.Client{Timeout: 15 * time.Second}
	}

	contentType := "text/plain"
	if isHTML {
		contentType = "text/html"
	}

	// SendGrid v3 mail/send API
	payload := map[string]any{
		"personalizations": []map[string]any{
			{"to": []map[string]string{{"email": to}}},
		},
		"from":    map[string]string{"email": "noreply@example.com"},
		"subject": subject,
		"content": []map[string]string{
			{"type": contentType, "value": body},
		},
	}

	bodyBytes, _ := json.Marshal(payload)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost,
		"https://api.sendgrid.com/v3/mail/send",
		bytes.NewReader(bodyBytes),
	)
	if err != nil {
		return "", fmt.Errorf("send_email(sendgrid): build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+p.apiKey)

	resp, err := p.client.Do(req)
	if err != nil {
		return "", fmt.Errorf("send_email(sendgrid): request failed: %w", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusAccepted, http.StatusOK:
		return resp.Header.Get("X-Message-Id"), nil
	case http.StatusUnauthorized:
		return "", errors.New("send_email(sendgrid): invalid API key — check SENDGRID_API_KEY")
	case http.StatusForbidden:
		return "", errors.New("send_email(sendgrid): forbidden — check sender verification at sendgrid.com")
	default:
		respBody, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("send_email(sendgrid): status %d: %s", resp.StatusCode, respBody)
	}
}

// ── Resend provider ───────────────────────────────────────────────

type resendProvider struct {
	apiKey string
	client *http.Client
}

func (p *resendProvider) name() string { return "resend" }

func (p *resendProvider) send(ctx context.Context, to, subject, body string, isHTML bool) (string, error) {
	if p.client == nil {
		p.client = &http.Client{Timeout: 15 * time.Second}
	}

	// Resend API — https://resend.com/docs/api-reference/emails/send-email
	payload := map[string]any{
		"to":      []string{to},
		"subject": subject,
	}
	if isHTML {
		payload["html"] = body
	} else {
		payload["text"] = body
	}

	bodyBytes, _ := json.Marshal(payload)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost,
		"https://api.resend.com/emails",
		bytes.NewReader(bodyBytes),
	)
	if err != nil {
		return "", fmt.Errorf("send_email(resend): build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+p.apiKey)

	resp, err := p.client.Do(req)
	if err != nil {
		return "", fmt.Errorf("send_email(resend): request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)

	switch resp.StatusCode {
	case http.StatusOK, http.StatusCreated:
		// Resend returns {"id": "..."}
		var result struct {
			ID string `json:"id"`
		}
		if err := json.Unmarshal(respBody, &result); err != nil {
			return "", nil // sent but couldn't parse ID — not fatal
		}
		return result.ID, nil
	case http.StatusUnauthorized:
		return "", fmt.Errorf("send_email(resend): invalid API key — check RESEND_API_KEY")
	default:
		return "", fmt.Errorf("send_email(resend): status %d: %s", resp.StatusCode, respBody)
	}
}

// ── from_email injection ──────────────────────────────────────────
// Both providers need from_email set on the request.
// We inject it from the SendEmailTool after the provider builds the payload.
// This is handled by overriding the send call per provider below.

// sendWithFrom wraps provider.send to inject the from address.
// Called by Execute instead of provider.send directly.
func (t *SendEmailTool) sendWithFrom(
	ctx context.Context,
	to, subject, body string,
	isHTML bool,
) (string, error) {
	switch p := t.provider.(type) {
	case *sendGridProvider:
		return p.sendFrom(ctx, t.fromEmail, t.fromName, to, subject, body, isHTML)
	case *resendProvider:
		return p.sendFrom(ctx, t.fromEmail, t.fromName, to, subject, body, isHTML)
	default:
		return t.provider.send(ctx, to, subject, body, isHTML)
	}
}

func (p *sendGridProvider) sendFrom(ctx context.Context, fromEmail, fromName, to, subject, body string, isHTML bool) (string, error) {
	if p.client == nil {
		p.client = &http.Client{Timeout: 15 * time.Second}
	}

	contentType := "text/plain"
	if isHTML {
		contentType = "text/html"
	}

	fromField := map[string]string{"email": fromEmail}
	if fromName != "" {
		fromField["name"] = fromName
	}

	payload := map[string]any{
		"personalizations": []map[string]any{
			{"to": []map[string]string{{"email": to}}},
		},
		"from":    fromField,
		"subject": subject,
		"content": []map[string]string{
			{"type": contentType, "value": body},
		},
	}

	bodyBytes, _ := json.Marshal(payload)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost,
		"https://api.sendgrid.com/v3/mail/send",
		bytes.NewReader(bodyBytes),
	)
	if err != nil {
		return "", fmt.Errorf("send_email(sendgrid): %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+p.apiKey)

	resp, err := p.client.Do(req)
	if err != nil {
		return "", fmt.Errorf("send_email(sendgrid): %w", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusAccepted, http.StatusOK:
		return resp.Header.Get("X-Message-Id"), nil
	case http.StatusUnauthorized:
		return "", errors.New("send_email(sendgrid): invalid API key")
	case http.StatusForbidden:
		return "", errors.New("send_email(sendgrid): forbidden — verify sender at sendgrid.com")
	default:
		rb, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("send_email(sendgrid): status %d: %s", resp.StatusCode, rb)
	}
}

func (p *resendProvider) sendFrom(ctx context.Context, fromEmail, fromName, to, subject, body string, isHTML bool) (string, error) {
	if p.client == nil {
		p.client = &http.Client{Timeout: 15 * time.Second}
	}

	from := fromEmail
	if fromName != "" {
		from = fromName + " <" + fromEmail + ">"
	}

	payload := map[string]any{
		"from":    from,
		"to":      []string{to},
		"subject": subject,
	}
	if isHTML {
		payload["html"] = body
	} else {
		payload["text"] = body
	}

	bodyBytes, _ := json.Marshal(payload)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost,
		"https://api.resend.com/emails",
		bytes.NewReader(bodyBytes),
	)
	if err != nil {
		return "", fmt.Errorf("send_email(resend): %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+p.apiKey)

	resp, err := p.client.Do(req)
	if err != nil {
		return "", fmt.Errorf("send_email(resend): %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	switch resp.StatusCode {
	case http.StatusOK, http.StatusCreated:
		var result struct {
			ID string `json:"id"`
		}
		json.Unmarshal(respBody, &result)
		return result.ID, nil
	case http.StatusUnauthorized:
		return "", errors.New("send_email(resend): invalid API key")
	default:
		return "", fmt.Errorf("send_email(resend): status %d: %s", resp.StatusCode, respBody)
	}
}

func init() {
	tools.RegisterBuiltin("send_email", func(cfg tools.ToolConfig) (tools.Tool, error) {
		if cfg.APIKey == "" {
			return nil, fmt.Errorf(
				"send_email requires an api_key\n" +
					"  sendgrid:  api_key: \"env:SENDGRID_API_KEY\"\n" +
					"  resend:    api_key: \"env:RESEND_API_KEY\"",
			)
		}

		fromEmail := cfg.Extra["from_email"]
		if fromEmail == "" {
			return nil, fmt.Errorf(
				"send_email requires extra.from_email in agents.yaml\n" +
					"  extra:\n" +
					"    from_email: \"agent@yourdomain.com\"",
			)
		}

		provider := cfg.Extra["provider"]
		if provider == "" {
			provider = "sendgrid"
		}

		fromName := cfg.Extra["from_name"]

		t, err := NewSendEmailTool(provider, cfg.APIKey, fromEmail, fromName)
		if err != nil {
			return nil, err
		}
		return t, nil
	})
}
